### ISSUE TITLE
Error on sign-up displayed RE Head, but sign-up apparently completes successfully 

### ISSUE THREAD

**Issue by airbr** [airbr/nzaa-dev#2]
**Update: Occurs visiting Minutes tab at all. **

Receiving this message on signup:

```
nzaa-dev/views/minutes/index.ejs:3 1| <!DOCTYPE html> 2| <html lang="en"> >> 3| <head> 4| <% include ../partials/head %> 5| </head> 6| Cannot read property 'approved' of undefined

TypeError: /Users/dev/webprojects/nzaa-dev/views/minutes/index.ejs:3
    1| <!DOCTYPE html>
    2| <html lang="en">
 >> 3| <head>
    4|   <% include ../partials/head %>
    5| </head>
    6| 

Cannot read property 'approved' of undefined
    at eval (eval at compile (/Users/dev/webprojects/nzaa-dev/node_modules/ejs/lib/ejs.js:464:12), <anonymous>:133:43)
    at eval (eval at compile (/Users/dev/webprojects/nzaa-dev/node_modules/ejs/lib/ejs.js:464:12), <anonymous>:151:9)
    at returnedFn (/Users/dev/webprojects/nzaa-dev/node_modules/ejs/lib/ejs.js:493:17)
    at View.exports.renderFile [as engine] (/Users/dev/webprojects/nzaa-dev/node_modules/ejs/lib/ejs.js:350:31)
    at View.render (/Users/dev/webprojects/nzaa-dev/node_modules/express/lib/view.js:126:8)
    at tryRender (/Users/dev/webprojects/nzaa-dev/node_modules/express/lib/application.js:639:10)
    at Function.render (/Users/dev/webprojects/nzaa-dev/node_modules/express/lib/application.js:591:3)
    at ServerResponse.render (/Users/dev/webprojects/nzaa-dev/node_modules/express/lib/response.js:961:7)
    at /Users/dev/webprojects/nzaa-dev/routes/minutes.js:36:9
    at newTickHandler (/Users/dev/webprojects/nzaa-dev/node_modules/mpromise/lib/promise.js:234:18)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by airbr** [comment]
Error occurs because no minutes are seeded... TODO...
